### ISSUE TITLE
Brumadinho says: Received donations  are enough for now and be careful with scam

### ISSUE THREAD

**Issue by clucasalcantara** [clucasalcantara/helpbrumadinho#4]
**Should we continue?**
https://www.bol.uol.com.br/noticias/2019/01/28/doacoes-a-brumadinho-sao-desnecessarias-dizem-bombeiros.htm

**Comment by caiojhonny** [comment]
I do not think so... we are late 😓

**Comment by clucasalcantara** [comment]
Agreed :/
